apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: vluid
          value: "$vluid"
        - name: vlph
          value: "$vlph"
        - name: vmuid
          value: "$vmuid"
        - name: vmph
          value: "$vmph"
        - name: shph
          value: "$shph"
